Update build to use Vite 4, update to api v12, workarounds for jewelry
Frostiae/Flyffulator pull request #69
Opened 2022-11-16 12:15 UTC by kirides

This PR includes the following changes:
- Updated deps
  - vite 4.0.0 -> 4.3.5
  - @vitejs/plugin-vue 4.0.0 -> 4.2.1
  - @vitejs/plugin-vue-jsx 3.0.0 -> 3.0.1
  - @vue/eslint-config-prettier 7.0.0 -> 7.1.0
  - eslint 8.22.0 -> 8.40.0
  - eslint-plugin-vue 9.3.0 -> 9.11.1
- legacy jewelry is now excluded
- upgradable jewelry is now supported (uses the same item ID but multiplied it by `100000`, allows to re-use persistence code)
- re-introduce PremiumItems
- load build, stats, equipment 

These changes are live and can be seen here: https://kirides.github.io/Flyffulator/

2023-04-18 19:35 UTC, MBrinks2239 commented
@kirides change line 32 in utils.js to maxLevel 140 so this can be used for higher level players. Idk if this will ever get merge but that way atleast we can use your site.

2023-04-18 19:37 UTC, kirides commented
I will update the game dataset and aswell as the max level once I get some time for it :)

2023-04-18 19:38 UTC, MBrinks2239 commented
That would be great, let me know if there is anything I can do

2023-04-19 20:41 UTC, kirides commented
i rebased the PR on the current main, now you can select levels up to 140.
I also updated all the data to use the latest v12 data (previously v9)

2023-05-01 10:43 UTC, MBrinks2239 commented
@Frostiae could you take a look at this PR?

2023-05-05 07:44 UTC, Frostiae commented
> @Frostiae could you take a look at this PR?

I will be trying to update to the damage-calc branch pretty soon which is also using vite and will look into this PR once that is done

2023-05-07 02:19 UTC, Frostiae requested changes
Now that the main branch is updated and using Vite already, do you think its possible to rebase onto that? Would mainly be interested in the jewelry changes and possibly premium items as well.  Thank you for the hard work!

2023-05-07 05:50 UTC, MBrinks2239 commented
@kirides Do you wanna rebase or do you want to redo the changes on the new main branch?

2023-05-07 05:56 UTC, kirides commented
I'll rebase the changes once I get to a computer.

2023-05-09 07:39 UTC, kirides commented
@Frostiae 

are the premium items broken on main currenty?
checking the mark doesn't show them, neither are they visible at all.

2023-05-09 16:56 UTC, Frostiae commented
> @Frostiae
> 
> are the premium items broken on main currenty? checking the mark doesn't show them, neither are they visible at all.
> 
> edit: i re-added rudimentary support for premium items back in. Persistence seems to be broken since the rework though.
> 
> level, checkboxes, etc. don't properly persist in builds.

Thanks, will take a look at the builds issue

2025-03-01 13:43 UTC, Frostiae commented
Obsolete due to 692a9fd3753adb410a68d6379eec59cad9302f6d

2025-03-01 13:43 UTC, closed without merging